### ISSUE TITLE
[Question]: Overlap with nvim-tree

### ISSUE THREAD

**Issue by yetone** [akinsho/bufferline.nvim#316] opened 2022-01-25 15:08 UTC
### What happened?

When I set the offset for the NvimTree file type, but it is overlapping.

![image](https://user-images.githubusercontent.com/1206493/151002275-3f065d4f-20cb-435b-90e1-398f109b5495.png)

my config is:

```lua
    bufferline.setup{
      options = {
        always_show_bufferline = false,
        diagnostics = 'nvim_lsp',
        diagnostics_indicator = function(count, level, diagnostics_dict, context)
          return "("..count..")"
        end,
        offsets = {
          {
            filetype = "NvimTree",
            text = "File Explorer",
            highlight = "Directory",
            text_align = "left"
          },
        },
      },
    }

```

### What did you expect to happen?

Do not overlap

### Additional Information

...

**Comment by akinsho** [comment] 2022-01-25 17:05
@yetone this is not a bug but just the default behaviour of nvim. The reason you are seeing the overlap is that you are using a window separator character that is in the middle of the cell, e.g. `|` that isn't likely the actual character but something else. This is not something this plugin can fix for you, since it depends on how you have set your window separator character. You can either accept it as is, or find a window separator ASCII character that is left or right aligned and use that instead. Patched fonts usually have something like that. That's something you can sort out in your config file.

**Comment by AlwynYin** [comment] 2022-01-25 17:23
**You can add a padding**
```lua
offsets = { { filetype = "NvimTree", text = "", padding = 1 } },
```
this one is copied from [This Neovim tutorial](https://github.com/LunarVim/Neovim-from-scratch/tree/08-treesitter)

**Comment by yetone** [comment] 2022-01-26 04:50
@akinsho I understand, thank you for your patience!

**Comment by yetone** [comment] 2022-01-26 04:50
@AlwynYin You are a great person, thank you very much!

**Comment by akinsho** [comment] 2022-01-26 09:46
Going to close this out 👍🏿

**Closed by akinsho** 2022-01-26 09:46 UTC
Labels: question
