### ISSUE TITLE
[Bug]:  Toggleterm breaks offset

### ISSUE THREAD

**Issue by Alex-vZyl** [akinsho/bufferline.nvim#540] opened 2022-09-06 19:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Here I have nvim-tree.lua open with the offset displaying correctly:

![image](https://user-images.githubusercontent.com/81622310/188718731-006997e1-ece9-4a63-9762-3ecfc11bbf36.png)

When I open the terminal (with toggleterm) the tree heading completely disappears:

![image](https://user-images.githubusercontent.com/81622310/188718768-0f6b7885-2b47-4ae8-be75-7df94eeab1ed.png)

I am unsure if this issue lies with bufferline or toggleterm, but luckily you wrote both of them :)

### What did you expect to happen?

The heading should stay where it is.

### Config

```lua
require 'bufferline'.setup {
    options = {    
        tab_size = 12, -- Minimum size.
        buffer_close_icon ='',
        max_name_length = 20,
        mode = "buffers",
        diagnostics = "coc",   
        diagnostics_indicator = function(count, level, diagnostics_dict, context)
            local s = " "
            for e, n in pairs(diagnostics_dict) do
                if e == 'error' then
                    s = s .. ' ' .. n
                elseif e == 'warning' then
                    s = s .. ' ' .. n
                end
            end
            return s
        end,
        offsets = { 
            {
                filetype = "NvimTree",
                text = "File Explorer",
                highlight = "Directory",
                text_align = "center"
            }
        },
        separator_style = "padded_slant",
    }
}

local Terminal  = require('toggleterm.terminal').Terminal
local fish = Terminal:new({ cmd = "fish", hidden = true, direction = "horizontal" })
function _fish_toggle()
  fish:toggle()
end
vim.api.nvim_set_keymap("n", "<F3>", "<Cmd>lua _fish_toggle()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("t", "<F3>", "<Cmd>lua _fish_toggle()<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("v", "<F3>", "<Cmd>lua _fish_toggle()<CR>", {noremap = true, silent = true})
```

### Additional Information

None.

### commit

Unsure where it started, but I am on 0b4b863244ef1369a8b9e4246dc95f8cdb5db026.

**Comment by akinsho** [comment] 2022-09-06 20:32
This is a duplicate of quite a few issues. It is a known limitation of this feature that it cannot handle window layouts where the vertical panel being offset doesn't actually extend the entire vertical length of the window, PRs welcome 🙏🏿  #241 #492.

**Closed by akinsho** 2022-09-06 20:32 UTC
Labels: bug, duplicate

**Comment by Alex-vZyl** [comment] 2022-09-06 22:40
Apologies for not spotting those issues :)  If I ever get around to understanding the inner workings of neovim I would love to submit a PR.
