### ISSUE TITLE
How to config can only show filename in bufferline

### ISSUE THREAD

**Issue by NEX-S** [akinsho/bufferline.nvim#531] opened 2022-09-01 21:18 UTC
![image](https://user-images.githubusercontent.com/97107165/188014624-fa9e8ca0-b8bc-4cca-888a-9a168c0beb30.png)

I wish to config bufferline to only show init.lua in bufferline ( not nvim/init.lua)

I've tried to use this to config it but seem not what I want.
```
        name_formatter = function (buf)
           return vim.fn.expand('%:t')
        end,
```

**Comment by akinsho** [comment] 2022-09-01 22:21
The indicator you see there is to mark a duplicated filename. It only appears when two buffers with the exact same name are open. There is no way to disable this, but there is a feature request to add it. So this is either a duplicate of #469. In either case the question has been answered and if a duplicate there is already a tracking issue.

**Closed by akinsho** 2022-09-01 22:21 UTC
