### ISSUE TITLE
[Bug]: bufferline doesn't respect nvim-web-devicons `default = false`

### ISSUE THREAD

**Issue by ourigen** [akinsho/bufferline.nvim#206] opened 2021-08-28 01:37 UTC
### What happened?

I believe by default, file types without an associated devicon will just not show the icon. It is as if I set this config:

```
require'nvim-web-devicons'.setup {
 default = false;
}
```

However, bufferline will still show the gray default icon. Other plugins such as lualine doesn't

Bufferline:
![bufferline](https://user-images.githubusercontent.com/79729735/131202127-ffad4c48-9b81-45b5-a511-035cec416b1e.png)

Lualine:
![lualine](https://user-images.githubusercontent.com/79729735/131202150-cf2a4d37-4f71-4008-92a8-dd789d3a38e8.png)

### What did you expect to happen?

For file types without an associated devicons, if `default = false`, then the icon for that buffer should be hidden

### Additional Information

...

**Comment by akinsho** [comment] 2021-08-28 09:05
@ourigen this isn't actually a bug, but by design. I wanted/needed the buffer icons for all tabs to be consistent, so the size of tabs were consistent, so I explicitly pass `{ default = true }` to devicons. Tbh this has been the case for the entirety of the plugin's life and hasn't been an issue. I don't really want to deal with adding logic to handle empty icons and the sizing/spacing issues that will come from that. You can use the override functionality of `devicons` to set the value of the default icon to an empty string or a space character on your end to see if that gives the desired result you want.

**Comment by akinsho** [comment] 2022-04-04 12:20
This should be fixed by #359 since (on `dev` for now) you can set `options.show_buffer_default_icon = false` I've described why I went for that approach in the PR description, but essentially I wanted a way to have the behaviour set specifically for this plugin rather than relying on global values, especially since that gives less choice e.g. enabled just in this plugin or disabled just in this plugin.

**Closed by akinsho** 2022-04-04 12:20 UTC
Labels: bug
