### ISSUE TITLE
Feature Request: Open buffer on the right of current one in the bufferline?

### ISSUE THREAD

**Issue by nyngwang** [akinsho/bufferline.nvim#314] opened 2022-01-22 14:12 UTC
As title. Currently the new opened buffer will be appended to the bufferline. What I want is to open the current next to & on the right the current one.

For exactly what I mean, you can checkout this Edge/Chrome plugin, there is an animation in this link: https://chrome.google.com/webstore/detail/open-tabs-next-to-current/gmpnnmonpnnmnhpdldahlekfofigiffh

**Comment by akinsho** [comment] 2022-01-23 00:02
Going to close this as a duplicate of https://github.com/akinsho/bufferline.nvim/issues/232 the user in that issue migrated to another plugin that provides this functionality. As I've mentioned in https://github.com/akinsho/bufferline.nvim/issues/307 I'm very busy with other things atm and really don't have time to work on this feature. If you or some other user wants to *help* by opening a PR that would be much appreciated

**Closed by akinsho** 2022-01-23 00:02 UTC

**Comment by nyngwang** [comment] 2022-01-23 10:03
@akinsho: Appreciate your time.
