### ISSUE TITLE
[Bug]: Highlights are no longer being set by default

### ISSUE THREAD

**Issue by FollieHiyuki** [akinsho/bufferline.nvim#512] opened 2022-08-16 16:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With the latest switch to `nvim_set_hl`, I can't get my custom theme of bufferline.nvim to work anymore.

### What did you expect to happen?

bufferline.nvim uses my custom theme instead of the default.

### Config

- Load custom theme with `nvim_set_hl` (e.g. `vim.api.nvim_set_hl(0, 'BufferLineFill', { bg = '#3b4252' })`
- Lazy-load bufferline.nvim (after setting the custom theme)

=> `bufferline.nvim` uses the default highlights instead of my custom theme.

### Additional Information

Setting highlights with `highlights` table works. Running `highlight! BufferLineFill ...` after loading bufferline.nvim also works. These behaviors are expected.

I want to keep my themes separated from the plugins config, hence they are loaded before running setup(). Is my workflow not supported or is it a bug?

### commit

https://github.com/akinsho/bufferline.nvim/commit/f248437e31b97f2a91173ee770b181b8d8ccdd42

**Comment by akinsho** [comment] 2022-08-16 17:55
@FollieHiyuki the workflow you are trying to use is not officially supported. Using `nvim_set_hl` to set your bufferline highlights means that when `bufferline.setup` is called, the plugin will use whatever highlights are set at that point. This plugin should be configured by setting the highlight objects so that all highlights are set *before* this plugin is loaded.

If you are trying to modularize your highlights, then I suggest you put them in a separate module and then require them inside the bufferline file.

I'm not currently going to change the way highlighting works, as this will be quite a big refactor and will requiring a lot of people to migrate their setups.

**Comment by will** [comment] 2022-08-17 00:30
For what it's worth I had no custom bufferline hilights in my config, and before f248437e31b97f2a91173ee770b181b8d8ccdd42 switching between light and dark backgrounds worked great, now bufferline only takes the dark theme, even when starting up in light and making sure that bufferline is setup() well after all colorscheme stuff is set.

I'm working on figuring out a workaround in the above linked issue from rose-pine, and I hope to find some solution, but figured I'd post here too

**Comment by akinsho** [comment] 2022-08-17 07:05
@will I don't believe this issue is related to yours as far as I can see. This is about using custom highlights outside bufferline's setup, and your case doesn't involve them at all. Regarding the commit you linked, this was a soft deprecation because gui* highlights all still work, so nothing should have stopped showing because of that.

Ultimately, a lot of people's setups are far too unpredictable for me to guess the outcome of any change I make at all. I'm personally able to switch highlights by changing background and am able to select different themes and have bufferline change.

I recommend confirming that this issue occurs with *multiple colorschemes* not just the one you are using. If you can reproduce it for multiple colorschemes then this might point to an issue in a change I made and should be opened as a separate issue. Otherwise, please discuss the issue with the specific theme author. I currently rotate through three colorschemes on my personal machine in light and dark mode and all are currently working

**Comment by FollieHiyuki** [comment] 2022-08-17 13:30
@akinsho thanks for the answer. 

I wonder would this change break lots of theme plugins in the wild. AFAIK theme plugins literally just do the same things as I do - define highlights for groups and applying them with `nvim_set_hl` or `:highlight` command. So, if the user set their theme before `bufferline.nvim`, the same behavior as mine will occur.

**Comment by akinsho** [comment] 2022-08-17 14:07
@FollieHiyuki I spoke incorrectly, although in this case I'm giving advice that is counter to how this plugin is intended to be used, setting your highlights before this plugin starts will not matter and really should never have done. When this plugin is loaded, it checks the highlights table *only* as the potential source of user colours.

It prefers anything set in the user highlights in the first instance, otherwise it *creates the highlights from scratch*. If the `themable = true` which is the default, each highlight is set as `default` which means that if there is an existing highlight already, the one being set by this plugin should be ignored. 

The only explanation for any change in behaviour is that the `themable` can you try changing https://github.com/akinsho/bufferline.nvim/commit/f248437e31b97f2a91173ee770b181b8d8ccdd42#diff-2c6c1de1123ba1d6b6e907b4bf2dd42453544bebaa741c091d52d3ae58a7a0c0L86

In your local version of the plugin to `true` and seeing if that changes anything

**Comment by akinsho** [comment] 2022-08-17 15:01
Ok I think I've realized the issue and there was a bug. It's subtle, so wasn't immediately obvious. Basically `default` wasn't being set any more which would explain both your issues, actually. Can you both try the `dev` branch I've pushed a fix there

**Comment by CroszJexx** [comment] 2022-08-17 15:57
I switched to the development branch and everything seems to be working fine again.

**Comment by FollieHiyuki** [comment] 2022-08-17 16:36
Just checked out just now. Confirmed working. Thanks for the effort.

**Comment by akinsho** [comment] 2022-08-17 17:45
This is now merged into main in #505 so will close this out

**Closed by akinsho** 2022-08-17 17:45 UTC
Labels: bug
