### ISSUE TITLE
[Feature Request]: Use relative buffer number for currently visible buffers

### ISSUE THREAD

**Issue by convers39** [akinsho/bufferline.nvim#594] opened 2022-10-23 02:45 UTC
### What?

<img width="996" alt="image" src="https://user-images.githubusercontent.com/42597395/197370517-7deee9f9-0858-4645-998b-14b0d9278371.png">

Currently we have buffer id or absolute buffer number as the prefix.

For the `go_to_buffer` function, the `absolute` argument indicates use the absolute buffer number or relative one.

I am wondering if it is possible to also use relative buffer number as the prefix.

### Why?

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/42597395/197370598-fd7a59cf-48ac-475e-a4c2-3c8f9f053ab9.png">

Since it is hard to count when using the `go_to_buffer` function with `absolute=false`. If there are 3 buffers hidden in the left, you have to calculate with 4-3, 5-3 to get the relative number then navigate to it.

**Comment by convers39** [comment] 2022-10-23 02:48
this should be possible to define a custom function for `numbers` as long as we can get the number of buffers hidden left/right from `opts`?

<img width="839" alt="image" src="https://user-images.githubusercontent.com/42597395/197370737-1951b7a8-ebb6-473d-bf91-eace15069a94.png">

**Comment by akinsho** [comment] 2022-10-24 08:23
@convers39 I'm going to close this out as it appears to be a duplicate of https://github.com/akinsho/bufferline.nvim/issues/249 which needs to be renamed. The idea is the same, i.e. showing the relative buffer position not the id or absolute number. Please have a read through that issue to see where we got to. TLDR someone needs to make a PR, as I don't use this feature and am unlikely to do it personally.

**Closed by akinsho** 2022-10-24 08:23 UTC
Labels: enhancement
