### ISSUE TITLE
[Bug]: always_show_bufferline causes sporadic error on startup

### ISSUE THREAD

**Issue by Machine-Maker** [akinsho/bufferline.nvim#749] opened 2023-05-07 04:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Seemingly randomly, starting up neovim in a directory `nvim .` displayed an error that took me a while to track down to bufferline. Just shows a simple in-line error displayed below. Nothing shows up in `:messages`, like a stack trace so I don't really know where to start to look for the cause. 

<img width="750" alt="image" src="https://user-images.githubusercontent.com/15055071/236656998-8420bdf9-81bf-46d1-b3b0-1b7b5de62003.png">

### What did you expect to happen?

No error on startup

### Config

```
local P = { "akinsho/bufferline.nvim" }
P.version = "*"

P.dependencies = { 
  "nvim-tree/nvim-web-devicons",
  "nvim-tree/nvim-tree.lua",
}

P.opts = {
  options = {
    always_show_bufferline = false,
    offsets = {
      {
        filetype = "NvimTree",
        text = function() return vim.fs.basename(vim.fn.getcwd()) .. "/" end,
        text_align = "left",
        highlight = "NvimTreeRootFolder",
      },
    },
  },
}

return P
```

via lazy.vim

### Additional Information

Have other plugins installed, probably the most relevant, are nvim-tree and gitsigns? Let me know if you need a more complete rundown. 

It maybe happens 10% of the time I startup a session, which is weird, maybe some sort of ordering issue that either I have or the plugin has?

**Comment by akinsho** [comment] 2023-05-07 08:48
@Machine-Maker I'm not really sure there's much I can do with this report. There's no clear error message from bufferline, there's no stack trace or clear mechanism for reproducing this. There are also no other similar reports.

What I suggest is trying to drill down into what exactly is triggering this bug. Ideally using a minimal nvim config so that other random plugins can be ruled out definitively.

In the interim I'm going to close this out as it's really not actionable for me in its current state. Feel free to post back here if you figure out a consistent way to reproduce this with a minimal init.lua

**Closed** 2023-05-07 08:48 UTC
Labels: bug

**Comment by Machine-Maker** [comment] 2023-05-07 16:05
Yeah, I realize that it's not super clear on what's happening. I thought maybe there'd be a way at for me to get some verbose logging on what the full error is? Or maybe someone more knowledgeable than me would recognize how an error is displayed like that and not in :messages. 

I will spin up a fresh nvim instance and slowly try to replicate my setup to find the issue.

**Comment by akinsho** [comment] 2023-05-07 16:53
@Machine-Maker the screenshot isn't super clear since I don't really know where that error message is, is it at the top of the page is it in the place where the tabline is. Really hard to say but that message string is definitely not from bufferline specifically. There is no string in the plugin that says anything like that. I'm not even sure if that's in a buffer or in your winbar.

Also regarding people pitching in unfortunately across my many plugins people sometimes try to open issues hoping someone else might jump in and I often leave things open for ages waiting for this but tbh it doesn't really happen that often. This could easily be open months/years waiting for that.

My very strong feeling on this issue is that there is a plugin conflict here and tbh I don't it's actually coming from bufferline. Sometimes uncaught errors in one plugin seem to get spat out by others (granted rarely but I've seen stacktraces that reference one thing but it's really just surfacing another plugins issue)

**Comment by Machine-Maker** [comment] 2023-05-07 17:18
Here is my full window just after running `nvim .` in a directory. 
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/15055071/236692522-15d470d6-5dad-482f-800f-85796d333d39.png">

The only buffer that is open, is nvim-tree, no other buffers. It looks to be below the winbar on the first line of nvim-tree, but as I said, it def only happens if I enable the always show bufferline. But like you said, it could be a conflict with nvim-tree.

**Comment by akinsho** [comment] 2023-05-07 18:18
I think the next best step would be to see if this reproduces without nvim-tree. i.e. are you seeing bufferline errors separately or only due to some interaction. AFAIK loads of bufferline uses use nvim tree and I haven't had reports like this 🤷🏾‍♂️
