### ISSUE TITLE
[Bug]: hiding icons doesn't work

### ISSUE THREAD

**Issue by alextes** [akinsho/bufferline.nvim#546] opened 2022-09-12 11:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am probably doing something wrong. Perhaps I can PR some docs to improve this.

Inside my packer config I have the following, yet I still get the close icon.

```
	use({
		"akinsho/bufferline.nvim",
		tag = "v2.*",
		config = function()
			require("bufferline").setup({
				options = {
					diagnostics = "nvim_lsp",
					show_buffer_close_icon = false,
					show_close_icon = false,
				},
			})
		end,
	})

```

### What did you expect to happen?

No close icon.

### Config

See above.

### Additional Information

...

**Comment by akinsho** [comment] 2022-09-12 14:41
@alextes there is a typo in the config name for the buffer icons it should be
```lua
      show_close_icon = false,
      show_buffer_close_icons = false,
```
These options are quite old, and I'm due to rename the `show_close_icon` → `show_tab(_indicator)_close_icon`. The reason for the plurals is that there are multiple buffer icons and only a single tab close icon. Will close this out as I've confirmed locally that with the right spelling things work as expected

**Closed by akinsho** 2022-09-12 14:41 UTC
Labels: bug

**Comment by alextes** [comment] 2022-09-12 14:54
I tried several things, read the docs twice, restarted a dozen times.. typo 🙈 .

Thanks Akin!
