### ISSUE TITLE
[Bug]: Error occured when opening the help page

### ISSUE THREAD

**Issue by lifei** [akinsho/bufferline.nvim#911] opened 2024-05-20 05:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Just type the `:help mouse` and we got the following error.

```
E5108: Error executing lua ...nvim/lazy/bufferline.nvim/lua/bufferline/diagnostics.lua:75: attempt to call field 'is_enabled' (a nil value)
stack traceback:
	...nvim/lazy/bufferline.nvim/lua/bufferline/diagnostics.lua:75: in function <...nvim/lazy/bufferline.nvim/lua/bufferline/diagnostics.lua:71>
	...nvim/lazy/bufferline.nvim/lua/bufferline/diagnostics.lua:139: in function 'get'
	...are/nvim/lazy/bufferline.nvim/lua/bufferline/buffers.lua:63: in function 'get_components'
	...local/share/nvim/lazy/bufferline.nvim/lua/bufferline.lua:56: in function <...local/share/nvim/lazy/bufferline.nvim/lua/bufferline.lua:54>
```

### What did you expect to happen?

No error

### Config

Default LazyVIM config

### Additional Information

...

**Comment by akinsho** [comment] 2024-05-20 08:40
This appears to be a duplicate of the numerous issues that have been opened around the deprecation of the `is_disabled` field. This is fixed in the latest version of the plugin on the main branch

**Closed by akinsho** 2024-05-20 08:40 UTC
Labels: bug, duplicate
