### ISSUE TITLE
[Bug]: buffer next to pinned buffer dissapears in the bufferline while switching buffers

### ISSUE THREAD

**Issue by 0xRZ** [akinsho/bufferline.nvim#420] opened 2022-05-13 08:12 UTC
### What happened?

problem description in the title

### What did you expect to happen?

buffer keeps displaying

### Additional Information

using bufferline.nvim v2.1.0, but it also happens on main branch.

Gif demonstrating problem:
![Peek 2022-05-13 10-55](https://user-images.githubusercontent.com/46892933/168240356-b274a9e9-e9f6-4e09-a471-bd664bc421b0.gif)

**Comment by akinsho** [comment] 2022-05-13 08:20
@0xRZ thanks for raising this, I might have seen it myself but can't get this to reproduce. Can you share exactly what you are doing to get it to happen consistently, since I can only debug it if I can reproduce it?

**Comment by 0xRZ** [comment] 2022-05-13 08:24
@akinsho Ok.
Here is init.vim i used:
```vim
call plug#begin()
Plug 'kyazdani42/nvim-web-devicons'
Plug 'akinsho/bufferline.nvim', { 'tag': 'v2.*' }
call plug#end()

lua << EOF
local groups = require('bufferline.groups')
require("bufferline").setup {
	options = {
		mode = "buffers",
		diagnostics = "nvim_lsp",
	    diagnostics_indicator = function(count, level)
			if level:match("error") then
				return "("..count..")"
			end
		end,
		indicator_icon = '',
		close_command = "BDelete %d",
		right_mouse_command = "BDelete! %d",
		show_close_icon = false,
		show_tab_indicators = true,
		offsets = {
			{
			    filetype = "NvimTree",
			    text = "File Explorer",
			    text_align = "center",
			},
			{
			    filetype = "Outline",
			    text = "Class viewer",
			    text_align = "center",
			},
		},
		groups = {
            items = {
                require('bufferline.groups').builtin.pinned:with({ icon = "" }),
            },
        },
	},
}
EOF
let mapleader = "\<Space>"
nnoremap <silent> <leader>h :BufferLineCyclePrev<CR>
nnoremap <silent> <leader>l :BufferLineCycleNext<CR>
nnoremap <silent> <leader>bp :BufferLineTogglePin<CR>
```

Steps i do:
1. Open 4 buffers.
2. Switch to third buffer.
3. Pin it.
4. Switch to pinned buffer.
5. Cycle next buffers (cycle left)
6. Seeing closest buffer to pinned one dissapear in the tabline.

**Comment by akinsho** [comment] 2022-05-17 06:01
I haven't actually been able to reproduce this yet despite the instruction above, let me know if there's anything else specific to tweak that might bring this on

**Comment by 0xRZ** [comment] 2022-05-17 16:24
@akinsho 

> if there's anything else specific to tweak that might bring this on

no i don't think so


Btw nvim --version i use is: `v0.8.0-dev+32-gf4f593b33`
i also made `init.vim` a bit clearer:
```vimscript
let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

call plug#begin(s:plug_dir)
Plug 'akinsho/bufferline.nvim'
call plug#end()
PlugInstall | quit

lua << EOF
local groups = require('bufferline.groups')
require("bufferline").setup {
	options = {
		groups = {
            items = {
                require('bufferline.groups').builtin.pinned:with({ icon = "" }),
            },
        },
	},
}
EOF

nnoremap <silent> <space>h :BufferLineCyclePrev<CR>
nnoremap <silent> <space>l :BufferLineCycleNext<CR>
nnoremap <silent> <Space>bp :BufferLineTogglePin<CR>

``` 

Steps i do is the same. 
Open 3 files. 
Pin first buffer. 
Cycle to third buffer 
Seeing second buffer dissapear from bufferline

![Peek 2022-05-17 19-22](https://user-images.githubusercontent.com/46892933/168860873-091abbcf-f23a-41aa-9b67-d5482408a478.gif)

**Comment by akinsho** [comment] 2022-05-18 11:29
@0xRZ I've now managed to reproduce the issue. The reason I couldn't originally see it is that it does not reproduce in dev where I add and develop most new features. It looks like this might now be resolved. Can you try the dev branch and see if the issue still occurs on that branch for you.

**Comment by 0xRZ** [comment] 2022-05-18 17:09
@akinsho yes, it does not happen on dev branch! Thank you

**Comment by akinsho** [comment] 2022-05-18 21:33
Going to close this out then if that's ok, since once dev is merged this should be resolved.

**Closed by akinsho** 2022-05-18 21:33 UTC
Labels: bug
