### ISSUE TITLE
[Question/feature request]: is there a way to style buffer name based on whether there is unsaved changes? 

### ISSUE THREAD

**Issue by devkvlt** [akinsho/bufferline.nvim#480] opened 2022-07-16 00:54 UTC
### What?

Instead of an icon indicating unsaved change, I'd like to be able to do that just with styling the name (e.g. make the name dark orange...)

### Why?

Because it's cleaner in my opinion.. and also a rather basic feature.

**Comment by akinsho** [comment] 2022-07-16 09:19
@devkvlt this is a duplicate of #75 so I'm going to close it in favour of that one. Feel free to read through what I mentioned in that issue. TLDR I don't mind this feature but don't personally have a need for this so have no personal incentive to implement it, but will take a PR for it I've explained how to go about it there

**Closed** 2022-07-16 09:19 UTC
Labels: duplicate

**Comment by devkvlt** [comment] 2022-07-16 12:26
Thanks
