### ISSUE TITLE
[Bug]: LSP diagnostics don't update after undo

### ISSUE THREAD

**Issue by d-miketa** [akinsho/bufferline.nvim#213] opened 2021-09-02 14:04 UTC
### What happened?

1. Cause something the LSP recognises as an error; both bufferline and any statusline correctly report it as such.
2. Hit `u` to undo said error. The statusline (lualine in my case) correctly removes said error, but bufferline keeps reporting it until `:w`, `:e` or similar actions.

### What did you expect to happen?

I'd expect bufferline to stay up with the statusline, i.e. remove the error indicator once it's been undone.

### Additional Information

...

**Comment by akinsho** [comment] 2021-09-02 14:08
Hi @d-miketa,

I've just had a quick look and I'm not actually able to reproduce this issue. Can you share your bufferline configuration. Maybe it has something to do with your setup.

**Comment by d-miketa** [comment] 2021-09-02 14:31
I'll go look into that. So far I've noticed it doesn't happen in small files or when I create an error after the `return` statement in Lua. So I think it may be happening when the LSP has to do some non-trivial thinking.

**Comment by akinsho** [comment] 2021-09-04 10:04
@d-miketa I think if this relates to the actual behaviour of the language server or neovim's get diagnostics function, then it's not really something I can solve here. The implementation for getting diagnostics is really straightforward. This plugin just calls `:h vim.lsp.diagnostic.get_all()` and that returns a table with the information, we don't really do anything that should affect undo.

Will close this out since I'm not able to reproduce it and I don't think there's anything I can do about it on the plugin side. Let me know if you find a clear reproduction that relates to this plugin specifically, it could be something about how `get_all` works whereas the statusline probably user buffer level diagnostics which is a different pathway, but won't work here since bufferline needs to know about all diagnostics

**Closed by akinsho** 2021-09-04 10:04 UTC
Labels: bug

**Comment by d-miketa** [comment] 2021-09-05 23:49
Alright, seems like a good shout. I'll be on the lookout but it is difficult to reproduce. And it could've been a plugin issue too (I've been going through a few recently). Sorry!
