### ISSUE TITLE
[Bug] elements missing in sorter function on latest commit

### ISSUE THREAD

**Issue by max397574** [akinsho/bufferline.nvim#337] opened 2022-03-14 11:01 UTC
Since the merge from dev there is an error.
I'm not sure yet when exactly it happens.
I get it when I save the file.
```


vim.lsp.buf.formatting_seq_sync: (sumneko_lua) timeout
vim.lsp.buf.formatting_seq_sync: (sumneko_lua) timeout
"lua/custom_highlights/everforest.lua" 9L, 326B written
E5108: Error executing lua ...ck/packer/opt/bufferline.nvim/lua/bufferline/sorters.lua:106: bad argument #1 to 'sort' (table expected, got nil)
stack traceback:
	[C]: in function 'sort'
	...ck/packer/opt/bufferline.nvim/lua/bufferline/sorters.lua:106: in function 'sorter'
	.../site/pack/packer/opt/bufferline.nvim/lua/bufferline.lua:96: in function <.../site/pack/packer/opt/bufferline.nvim/lua/bufferline.lua:88>
```

**Comment by akinsho** [comment] 2022-03-14 12:07
@max397574 can you please include specific information about what your bufferline config is it looks like the sorter is broken but I can't tell anymore than that

**Comment by max397574** [comment] 2022-03-14 12:10
```lua
require("bufferline").setup({
    options = {
        mode = "buffers",
        diagnostics = "nvim_diagnostic",
        always_show_bufferline = false,
        custom_areas = {
            right = function()
                local diagnostics = vim.diagnostic.get(0)
                local count = { 0, 0, 0, 0 }
                for _, diagnostic in ipairs(diagnostics) do
                    count[diagnostic.severity] = count[diagnostic.severity] + 1
                end
                local result = {}

                if count[1] ~= 0 then
                    table.insert(result, {
                        text = "  " .. count[1],
                        guifg = vim.g.terminal_color_9,
                        guibg = colors.black,
                    })
                end

                if count[2] ~= 0 then
                    table.insert(result, {
                        text = "  " .. count[2],
                        guifg = vim.g.terminal_color_3,
                        guibg = colors.black,
                    })
                end

                if count[4] ~= 0 then
                    table.insert(result, {
                        text = "  " .. count[4],
                        guifg = vim.g.terminal_color_4,
                        guibg = colors.black,
                    })
                end

                if count[3] ~= 0 then
                    table.insert(result, {
                        text = "  " .. count[3],
                        guifg = vim.g.terminal_color_6,
                        guibg = colors.black,
                    })
                end
                return result
            end,
        },
    },
})
```

**Comment by max397574** [comment] 2022-03-14 12:11
also
it doesn't always happen when bufferline opens (when I open a second buffer)

Idk when it resorts things
if you could tell me I could test if it only happens then

**Comment by akinsho** [comment] 2022-03-14 12:20
@max397574 I can't reproduce this, and I'm not sure I fully understand it either. It seems to an error with the sort function as bufferline thinks it has no tab/buffers open so is passing `nil` to the sort function. Bufferline re-sorts buffers on every redraw which happens whenever things change in nvim e.g. buffers opened or windows opened etc.

**Comment by akinsho** [comment] 2022-03-14 12:21
If you could work out specifically when this is happening, so I can reproduce then I'll be able to fix it, but without a reproduction I can't fix it.

**Comment by akinsho** [comment] 2022-03-14 12:26
Can you reproduce this issue with a minimal `init.lua` i.e. no other plugins, just to make sure there isn't some new interaction with some other plugin you have

**Comment by max397574** [comment] 2022-03-14 12:35
to me it happens when I format with null-ls on save

**Comment by max397574** [comment] 2022-03-14 12:48
I got a minimal example (this is just en example, there are other cases when this happens, not only telescope help tags)
```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            "akinsho/bufferline.nvim",
            {
                "nvim-telescope/telescope.nvim",
                requires = {
                    "nvim-lua/plenary.nvim",
                },
            },
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. "/plugin/packer_compiled.lua",
            display = { non_interactive = true },
        },
    })
end

_G.load_config = function()
    require("bufferline").setup({
        options = {
            mode = "buffers",
            diagnostics = "nvim_diagnostic",
            always_show_bufferline = false,
        },
    })
end
-- if vim.fn.isdirectory(install_path) == 0 then
print("Installing Telescope and dependencies.")
vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
-- end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

use `Telescope help_tags` and select anything

**Comment by akinsho** [comment] 2022-03-14 13:52
@max397574 I've just tried with a simpler minimal init file and cannot reproduce this issue still. I used
```lua
vim.cmd("packadd local-bufferline.nvim")
vim.cmd("packadd telescope.nvim")
vim.cmd("packadd plenary.nvim")

require("bufferline").setup({
	options = {
		mode = "buffers",
		diagnostics = "nvim_diagnostic",
		always_show_bufferline = false,
	},
})

require("telescope").setup()
```
I think keeping packer out of this will be better, since that involves its own can of worms.

You can use this with `nvim -u <file-above> --noplugin`

**Comment by max397574** [comment] 2022-03-14 14:50
so u don't get the error if u use my minimal config?

**Comment by akinsho** [comment] 2022-03-14 17:12
Just to clarify, do either or you see this issue without packer? Can you both try the minimal config I provided and see if that still reproduces the issue? As far as I can see, my minimal  config is the same as yours without involving packer which shouldn't be required since that indicates the bug is not exclusively with this plugin since it should reproduce even without packer

**Comment by akinsho** [comment] 2022-03-14 17:33
@max397574 are you running it with `nvim -u <file-above> --noplugin` if you use the `--noplugin` flag vim will not load any plugins except something you packadd manually

**Comment by max397574** [comment] 2022-03-14 17:36
now I did
and I get the error

**Comment by max397574** [comment] 2022-03-14 17:37
since it then definitely has nothing to do with packer you should perhaps rather use my minimal config, since then we can be sure that we both use the same version of bufferline.nvim

**Comment by akinsho** [comment] 2022-03-14 17:47
That reproduce it for me @max397574 thanks for that 👍🏿 I can start to look into it now 👀

**Comment by vsedov** [comment] 2022-03-14 18:55
> @max397574 this should now be fixed can you let me know if the latest commit resolved this issue.

Working on my end, thanks :)

**Comment by akinsho** [comment] 2022-03-14 18:57
Gonna optimistically close this out thanks for reporting back @vsedov, if it's not fixed on your end let me know @max397574

**Closed by akinsho** 2022-03-14 18:57 UTC

**Comment by max397574** [comment] 2022-03-14 19:06
fixed for me as well 👍
