### ISSUE TITLE
[Bug]: Random close icon in bufferline

### ISSUE THREAD

**Issue by jacobrreed** [akinsho/bufferline.nvim#853] opened 2024-01-24 15:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/akinsho/bufferline.nvim/assets/25580051/68275acd-2bc5-4acd-878b-6eeaf61235df)

For some reason this random close icon is at the far right of my bufferline? I also have show_buffer_close_icons: false anyways, so not sure why its rendering them at all?

### What did you expect to happen?

I expect it to not be there

### Config

```
return {
  "akinsho/bufferline.nvim",
  version = "*",
  lazy = false,
  dependencies = { "nvim-tree/nvim-web-devicons", "famiu/bufdelete.nvim" },
  opts = {
    options = {
      mode = "buffers",
      show_buffer_close_icons = false,
      show_tab_indicators = false,
      max_name_length = 26,
      diagnostics = "nvim_lsp",
      diagnostics_update_in_insert = true,
      offsets = {
        {
          filetype = "neo-tree",
          text = "Neo-tree",
          highlight = "Directory",
          text_align = "left",
        },
      },
    },
  },
  keys = {
    { "<leader>bp", "<Cmd>BufferLineTogglePin<CR>", desc = "Toggle pin" },
    { "<leader>bP", "<Cmd>BufferLineGroupClose ungrouped<CR>", desc = "Delete non-pinned buffers" },
    { "<leader>bo", "<Cmd>BufferLineCloseOthers<CR>", desc = "Delete other buffers" },
    { "<leader>br", "<Cmd>BufferLineCloseRight<CR>", desc = "Delete buffers to the right" },
    { "<leader>bl", "<Cmd>BufferLineCloseLeft<CR>", desc = "Delete buffers to the left" },
    { "<S-h>", "<cmd>BufferLineCyclePrev<cr>", desc = "Prev buffer" },
    { "<S-l>", "<cmd>BufferLineCycleNext<cr>", desc = "Next buffer" },
    { "[b", "<cmd>bprevious<cr>", desc = "Prev buffer" },
    { "]b", "<cmd>bnext<cr>", desc = "Next buffer" },
    { "<leader>bd", "<cmd>Bdelete<cr>", desc = "Delete current buffer" },
  },
}

```

### Additional Information

...

**Comment by akinsho** [comment] 2024-01-25 11:00
This is not a bug and is there by design that button is there for closing tabpages. There is also a setting which I don't remember off hand to remove it if you so choose

**Closed by akinsho** 2024-01-25 11:00 UTC
Labels: bug

**Comment by jacobrreed** [comment] 2024-01-25 14:38
` show_tab_indicators = true | false,` I assume, thanks @akinsho
