### ISSUE TITLE
[bug]: custom filter regression

### ISSUE THREAD

**Issue by smichaud** [akinsho/bufferline.nvim#176] opened 2021-08-04 13:26 UTC
I don't know if this is possible to hide some buffer from the line?
I would like to hide buffers when &buftype == quickfix || &buftype == terminal.
I am sorry if I missed the configuration for this.

**Comment by akinsho** [comment] 2021-08-04 13:38
Hi @smichaud,
This is already possible using the `custom_filter` key. You can find more information in the help docs under `:help bufferline-lua-filtering`. You declare function and set it to the value of this key. The docs has an example which you can take inspiration from.

Alternatively you can make both of those buffers `nobuflisted` using an autocommand and that way bufferline will also skip them.

**Comment by akinsho** [comment] 2021-08-04 13:39
Sorry re. closing the issue so fast btw, I try to be proactive about closing an issue if there is definitely a solution that I can/have already referenced, rather than leaving them since I don't like things lingering.

**Comment by smichaud** [comment] 2021-08-04 15:39
Hum... I added my filters, but it does not work:
```
        custom_filter = function(buf_number)
            if vim.bo[buf_number].filetype ~= "qf" then return true end
            if vim.bo[buf_number].filetype ~= "neoterm" then return true end
        end,
```

I made sure this was right by running `:lua print(vim.bo.filetype)` and I indeed have `qf` for quickfix and `neoterm` for my terminals, but they still show in the tab line.

**Comment by akinsho** [comment] 2021-08-04 16:08
@smichaud can you verify your filter is in the right place in your settings by trying something wild like just returning `false`. That should remove every buffer and render an empty bufferline.

It might be there's been a regression with that field, although I think it's important to note that for things like plugins the point at which they set a filetype might be after the buffer is created and added to bufferline, in which case it won't catch this. 

I'll have a look when I get some free time but another way to do this is creating a `ftplugin/qf.lua` and adding the `buflisted = false` setting for all qf buffers and all neoterm buffers.

**Comment by smichaud** [comment] 2021-08-04 16:49
I tried to return false and there is indeed no buffer displayed.
I used this instead in my init.vim: 
```
autocmd FileType neoterm set nobuflisted
autocmd FileType qf set nobuflisted
```
This solve my problem, but I think it would better to find out why it does not work using the custom filters.

**Comment by akinsho** [comment] 2021-08-05 07:07
@smichaud it would definitely be good to figure out the issue with custom filters, my time is limited though so will not be able to jump on this for a bit. I did some quick debugging, and it seems that some of the filetype values for buffers are not actually set by vim, which is why your comparison fails. Can you print the value of `vim.bo[buf].filetype` on your end to confirm this is happening.

**Comment by smichaud** [comment] 2021-08-08 15:15
Adding : `vim.fn.input(vim.bo[buf_number].filetype)` in the custom_filter
function never shows *neoterm* or *qf* (it shows others like python), but using
`echo luaeval('vim.bo[MY_NEOTERM_OR_QF'].filetype)` shows *qf* and *neoterm*
properly. I am not sure I answered your question here, did I?

**Comment by akinsho** [comment] 2021-08-08 17:54
@smichaud thanks for clarifying. This does seem to be a result of some strange behaviour in nvim around getting buffer filetypes, not sure what to do about it just yet but will look into it when I get some time unless someone else decides to help out first.

**Comment by akinsho** [comment] 2021-09-10 17:56
@smichaud I finally had time to look into this again and confirmed that this bug is an upstream issue, not one with this plugin. For whatever reason, nvim doesn't return the right values when using `vim.bo[id]` or `nvim_buf_get_option(id, value)` *until* a buffer has been entered. The logic which belongs to this plugin i.e. showing or hiding a buffer based on returning true or false from this function though does work. I think regarding the lua api behaviour, that is better reported upstream

**Closed by akinsho** 2021-09-10 17:56 UTC
