### ISSUE TITLE
[Bug]: Icons disappeared after the update

### ISSUE THREAD

**Issue by Ddystopia** [akinsho/bufferline.nvim#561] opened 2022-09-21 19:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've updated plugin, then it showed me that guifg and etc are now deprecated. I changed to new values, but my icons disappeared.
This is my config before(when icons were) and after:
Before
```lua
  use {
    'akinsho/nvim-bufferline.lua',
    requires = 'kyazdani42/nvim-web-devicons',
    config = function()
      local b = require("bufferline")
      b.setup {
        options = {
          --      mappings = false,
          diagnostics = "nvim_diagnostic",
          show_buffer_close_icons = false,
          always_show_bufferline = false
        },
        highlights = { fill = { guibg = '#21222C' }, buffer_selected = { gui = 'bold' } }
      }
    end
  }
```
After:
```lua
  use {
    'akinsho/nvim-bufferline.lua',
    tag = 'v2.*',
    requires = 'kyazdani42/nvim-web-devicons',
    config = function()
      local b = require("bufferline")
      b.setup {
        options = {
          --      mappings = false,
          diagnostics = "nvim_lsp",
          show_buffer_icons = true,
          show_buffer_close_icons = false,
          show_close_icon = false,
          always_show_bufferline = true
        },
        highlights = {
          fill = { bg = '#21222C' },
          buffer_selected = { bold = true, italic = false }
        }
      }
    end
  }
```

### What did you expect to happen?

For me to have icons

### Config

```lua
  use {
    'akinsho/nvim-bufferline.lua',
    tag = 'v2.*',
    requires = 'kyazdani42/nvim-web-devicons',
    config = function()
      local b = require("bufferline")
      b.setup {
        options = {
          --      mappings = false,
          diagnostics = "nvim_lsp",
          show_buffer_icons = true,
          show_buffer_close_icons = false,
          show_close_icon = false,
          always_show_bufferline = true
        },
        highlights = {
          fill = { bg = '#21222C' },
          buffer_selected = { bold = true, italic = false }
        }
      }
    end
  }
```

### Additional Information

...

**Comment by akinsho** [comment] 2022-09-21 20:11
@Ddystopia I just used your configuration and my icons appear without issue?

**Comment by akinsho** [comment] 2022-09-21 20:12
Presumably you mean your buffer filetype icons, correct? Since you didn't specify what icon you meant. FWIW you need to make sure your version of the devicons plugin is also up to date.

**Comment by Ddystopia** [comment] 2022-09-21 20:31
This is what I see now.
![image](https://user-images.githubusercontent.com/63151578/191604336-e67462f7-5ffa-4401-b031-239c48ae50e2.png)

**Comment by akinsho** [comment] 2022-09-21 20:41
@Ddystopia can you confirm what commit of the plugin you are using? can you also confirm that nvim web devicons is running correctly and showing up for other plugins

**Comment by akinsho** [comment] 2022-09-22 07:00
@Ddystopia can you provide this information? Otherwise, I will close this issue. When you have a reproduction that I can use to definitely trigger this issue, feel free to post back here

**Comment by Ddystopia** [comment] 2022-09-22 08:31
I will but not now, I'm sorry.

**Comment by akinsho** [comment] 2022-09-22 11:08
Ok will close this out till you have a reproduction I can use, feel free to comment back on here when you do, and I'll re-open it.

**Closed by akinsho** 2022-09-22 11:08 UTC
Labels: bug

**Comment by ChangqingW** [comment] 2022-10-08 06:05
I had a similar config and bufferline was showing icons until packer moved nvim-web-devicons from start to opt folder (not sure why it did that). Having `use 'kyazdani42/nvim-web-devicons'` forced it back to the start folder and restored the icons.
