### ISSUE TITLE
[Bug]: Icon for man page not shown in bufferline

### ISSUE THREAD

**Issue by samEngineering** [akinsho/bufferline.nvim#699] opened 2023-03-01 20:52 UTC
I use nvim for my man pager via the environment variable 
` export MANPAGER="nvim +Man! -c ':set signcolumn=auto'"`

I don't get the icon for man pages in the bufferline, though. All other icons are showing. 
I thought this was originally an issue with `nvim-web-devicons`, but the icon setting can be verified as correct with some built-in commands. This issue is discussed on the `nvim-web-devicons` guthub page:
https://github.com/nvim-tree/nvim-web-devicons/issues/210#issuecomment-1447462598

I'm not sure if this is related, but each icon background color seems to be fixed to the background color of my colorscheme even when the tab color changes. I tried setting the bufferline colors as suggested in the documentation but I only ever say the default colors. I resorted to setting the `BufferLine<...>` highlight grous with the `vim.api.nvim_set_hl` function. My base groups `TabLine<...>` are also set. I've read another bug report about this issue and the user is directed to `nvim-web-devicons`.

### What did you expect to happen?

Icon for man page shown in bufferline

### Config

```{lua}
local status, bufferline = pcall(require, "bufferline")
if not status then
   return
end


bufferline.setup({
   options = {
      mode = "tabs",
      numbers = "none",

      close_icon = false,
      left_truc_marker = false,
      right_truc_marker = false,
      modified_icon = "",

      max_name_length = 18,
      max_prefix_length = 15,
      truncate_names = true,
      tab_size = 25,

      diagnostics = false,
      diagnostics_update_in_insert = false,

      color_icons = true,
      show_buffer_icons = true,
      show_buffer_default_icon = false,
      show_buffer_close_icons = false,
      show_close_icon = false,
      show_tab_indicators = false,
      show_duplicate_prefix = true,

      separator_style = "slant",
      enforce_regular_tabs = true,
      always_show_bufferline = true,

      hover = {
          enabled = false,
      },
   }
})
```

**Comment by akinsho** [comment] 2023-03-01 22:27
@samEngineering there are a few things put together in this issue but I'll just focus on the override icon not working. This is actually a duplicate of a much older issue https://github.com/akinsho/bufferline.nvim/issues/191 feel free to have a read through and see where that go to.

Another potential solution is a new option I added to the `dev` branch which allows a user to decide how getting icons is resolved. I don't remember exactly what the name is but it is one of the most recent commits on dev. That could provide you with a work around.

If you want to discuss this more please comment over on the original issue. I'll close this out now in favour of that one though

**Closed by akinsho** 2023-03-01 22:27 UTC
Labels: bug
