### ISSUE TITLE
[Feature request]:  Is there a way to numbering with N.th?

### ISSUE THREAD

**Issue by 66RING** [akinsho/bufferline.nvim#291] opened 2022-01-06 04:06 UTC
### What happened?

Thanks for your awesome work.👍

I want bufferline always be numbered 1th,2th,3th...Nth, so that I can easily get a number and use BufferLineGoToBuffer N.

always numbering with N.th:

```
<- (30) | 1.buf1 | 2.buf2 | 3.buf3 |(24) ->

| 1.buf2 | 2.buf1 | 3.buf3 |(24) ->

<- (30) | 1.buf3 | 2.buf1 | 3.buf2 |
```

### What did you expect to happen?

```
| 1.buf1 | 2.buf2 | 3.buf3 | 
```

1. go to buf2
2. number is 2
2. : BufferLineGoToBuffer 2

```
| 1.buf2 | 2.buf1 | 3.buf3 |
````

1. go to buf1
2. number is 2
2. : BufferLineGoToBuffer 2

**Comment by akinsho** [comment] 2022-01-06 10:01
Hi @66RING,

I'm not sure I understand, currently the numbers are up to the user and can be the visible number or the buffer number, if you use the buffer number you can just use `:b<bufnum>` otherwise `:BufferLineGotoBuffer <visiblenum>` will take you to the visible buffer. I can't tell from the above description what doesn't work or which way things should.

**Comment by 66RING** [comment] 2022-01-06 11:56
My bad. My english is not good enough and I missed the point. I mean using the `numbers=visiblenum` may get a better workflow. The demand should be the same as this #249.

kind of

```lua
require('bufferline').setup{
    options.numbers = visiblenum
}
```

My shortcut:

```lua
map <BS> :lua require"bufferline".go_to_buffer(vim.v.count)<CR>
```

If use `:b<bufnum>` , I need to press key more than twice often. Such as `22<BS>`, 22 is the buffer number and I need to press three key `2, 2, <BS>`.

![image](https://user-images.githubusercontent.com/49358576/148379310-43f0d90a-2a21-4f35-974a-fe0137543fa3.png)


If use `BufferLineGoToBuffer`, since `BufferLineGoToBuffer 4` will go to the **4th** buffer, I have to figure out which position is the 4th.

So, if  `options.numbers = visiblenum` I will know where is the 4th position at a glance and press two key only `{1..7}<BS>`.

**Comment by carsin** [comment] 2022-01-17 04:27
any update on this? i also find the default behavior very unnatural

**Comment by akinsho** [comment] 2022-01-17 09:41
@carsin or @66RING either of you are very welcome to submit a PR to help implement this. 
I'm quite busy and really don't have time to implement the all the many feature requests that are made across all my repos in a timely fashion but users who want these features can help by providing the functionality themselves.

I'm going to close this as a duplicate of #249 which I believe explains the issue more clearly

**Closed by akinsho** 2022-01-17 09:41 UTC
Labels: bug

**Comment by 66RING** [comment] 2022-01-17 14:25
Hi @akinsho ,

I think I found the bug. It seems that render function be called before sorter function and it render a worry number finally. 

I have tried to submit a PR, which simply move sorter function forward. But I stopped because I know nothing about the group feature.

```diff
diff --git a/lua/bufferline.lua b/lua/bufferline.lua
index f735b51..b46971a 100644
--- a/lua/bufferline.lua
+++ b/lua/bufferline.lua
@@ -942,12 +942,6 @@ local function render(components, tabpages, config)
     - tabs_length
     - close_length
 
-  if config:enabled("groups") then
-    components = require("bufferline.groups").render(components, sorter)
-  else
-    components = sorter(components)
-  end
-
   local before, current, after = get_sections(components)
   local line, marker, visible_components = truncate(before, current, after, available_width, {
     left_count = 0,
@@ -1030,6 +1024,13 @@ local function bufferline(config)
     buffers[i] = buf
   end
 
+  if config:enabled("groups") then
+    buffers = require("bufferline.groups").render(buffers, sorter)
+  else
+    buffers = sorter(buffers)
+  end
+
+
   local deduplicated = duplicates.mark(buffers)
   buffers = vim.tbl_map(function(buf)
     buf.component, buf.length = render_buffer(config, buf)
```

Here is my test.

```diff
diff --git a/lua/bufferline/numbers.lua b/lua/bufferline/numbers.lua
index 7750413..86c302f 100644
--- a/lua/bufferline/numbers.lua
+++ b/lua/bufferline/numbers.lua
@@ -121,6 +121,8 @@ function M.component(context)
     return context
   end
   local number_prefix = prefix(buffer, options.numbers, options.number_style)
+  print("numbers.component()", buffer.ordinal, vim.fn.bufname(buffer.id))
+  print(debug.traceback("====== numbers.Component() ========"))
   local number_component = ""
   if number_prefix ~= "" then
     number_component = number_prefix .. constants.padding
diff --git a/lua/bufferline/sorters.lua b/lua/bufferline/sorters.lua
index 929f20f..84567fb 100644
--- a/lua/bufferline/sorters.lua
+++ b/lua/bufferline/sorters.lua
@@ -102,6 +102,8 @@ function M.sort_buffers(sort_by, buffers)
   end
   for index, buf in ipairs(buffers) do
     buf.ordinal = index
+	print("sort_buffers", buf.ordinal, vim.fn.bufname(buf.id))
+	print(debug.traceback("====== sorter.lua:sort_buffers() ========"))
   end
 end
```

Open three file, buffer jump a bit and you will see `message` like this. 

It said render be call before sorter call, triggered by `vim.tbl_map`:

![image](https://user-images.githubusercontent.com/49358576/149778605-f8f90d71-6c90-4013-aa37-cb469d5da3f2.png)

![image](https://user-images.githubusercontent.com/49358576/149780477-cfca01af-45b4-40b6-8397-154ed62c039a.png)


After `sort_buffer`, all buffer wll get a new `ordinal` number. But since it is called before render it do not work well.

```lua
function M.sort_buffers(sort_by, buffers)
  ...
  for index, buf in ipairs(buffers) do
    buf.ordinal = index
  end
end
```

Here is my config


```lua
  require('bufferline').setup{
    options = {
      modified_icon = '',
      buffer_close_icon = '',
      show_buffer_close_icons = false,
      close_icon = "",
	  persist_buffer_sort = true,
	  sort_by = "tabs",
      always_show_bufferline = false,
      separator_style = {'', ''},
	  indicator_icon = '',
	  numbers = function(opts)
		return string.format('%s', opts.ordinal)
	  end,
      view = "multiwindow",
    },
    highlights = {
      buffer_selected = {
          guifg = '#61AFEF',
          gui = "bold"
      },
    }
  }
```

**Comment by akinsho** [comment] 2022-01-18 12:04
@66RING thanks for having a look 👍🏿 can we please move the conversation here to the original issue. I've actually already described that it isn't actually a bug of the current behaviour but a new feature since we render before the sorting because before it didn't matter but now it seems like we would like to render both times before and after sorting. We have to render early so we can get the size of the tab. Anyway this is all discussed in the other issue so this would make more sense to discuss in #249
