### ISSUE TITLE
[Bug]: Closing prompt buffers results in opening insert mode after every command

### ISSUE THREAD

**Issue by t-troebst** [akinsho/bufferline.nvim#710] opened 2023-03-12 01:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

To reproduce, source the following file:

```lua
local function handler(text)
    if text == "exit" then
        vim.api.nvim_command("close")
    end
end

local buf = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_option(buf, "buftype", "prompt")
vim.fn.prompt_setcallback(buf, handler)
vim.api.nvim_command("belowright split")
vim.api.nvim_win_set_buf(0, buf)
vim.api.nvim_command("startinsert")
```

This will open a prompt buffer in insert mode. Now type "exit" and hit enter to close the prompt. Now neovim enters insert mode after every command. Even just typing `:<CR>` will enter insert mode. I ran into this issue while using the REPL from [nvim-dap](https://github.com/mfussenegger/nvim-dap) though I expect other REPL-based plugins will have similar issues.

If `always_show_bufferline = false` is set, then after closing a prompt buffer, the issue happens if and only if the bufferline is actually open.

### What did you expect to happen?

Command mode should continue working as expected and not drop me into insert mode.

### Config

This reproduces with the barebones config and no other plugins:

```lua
vim.opt.termguicolors = true
require("bufferline").setup {}
```

### Additional Information

OS: Manjaro 22.0.4 / Ubuntu 22.04.1 LTS
nvim: 0.8.3
bufferline: 3677aceb9a72630b0613e56516c8f7151b86f95c (most recent)

**Comment by akinsho** [comment] 2023-03-12 07:52
@t-troebst this sounds a great deal like a potentially upstream issue as what you're describing is well outside the wheelhouse of this plugin and is nothing this plugin is even involved in. Can you try to see if this problem reproduces with the native built-in tabline.

Since I really don't think there is any logic in the entire plugin that relates to this

**Comment by t-troebst** [comment] 2023-03-12 21:12
I totally agree with you that it seems that there is upstream issue hiding somewhere. After I isolated the issue to this plugin, I had a look through the code to see if I can spot some auto command or something that could do this but I didn't find anything.

However, I did try to do the same thing with the native tabline and also with the barbar plugin which is similar to bufferline. Only this plugin triggers the issue.

**Comment by t-troebst** [comment] 2023-03-12 21:25
I was able to find an old version of the plugin that doesn't have the issue, using `git bisect` I isolated it to this commit: b1751849885c83b1381486247e9e6ae2f23ff14f. Something with the window offsets? I'll see if I can find the exact issue.

**Comment by t-troebst** [comment] 2023-03-13 01:52
I've identified the issue with upstream: https://github.com/vim/vim/issues/12147#issue-1620602719 In some API functions, vim/neovim temporarily switch to a buffer to query a local property / make a change. There is a bug in the way this context switch happens so insert mode doesn't get stopped when leaving the prompt buffer.

A workaround would be to replace `vim.bo[buf_num].buflisted` by `vim.api.nvim_buf_get_option(buf_num, "buflisted")`. That doesn't do the buggy context switch. Bonus effect: it's probably faster.

**Comment by akinsho** [comment] 2023-03-13 11:46
@t-troebst thanks for digging in and finding this issue 👍🏿, sounds kind of gnarly. I hope/expect there is a tracking neovim issue somewhere for this.

Regarding the potential workaround, I don't think that will work. `vim.bo` and the like are just using metamethods like `__newindex` to essentially call the same underlying APIs. Also the `get_option` method is going to be deprecated in favour of `nvim_buf_get_option_value`. All in all I think it will result in the same issue and I don't think it's any faster. From what I've heard nvim core contributors say they tend to point people towards these metatables in the first place.

**Comment by t-troebst** [comment] 2023-03-13 17:32
It does work because `nvim_buf_get_option` uses a different technique of getting the buffer local variable than `vim.bo` (which uses `nvim_buf_get_option_value` internally). The latter does this unnecessary context switch which can mess up the state and is (presumably) slower. Looks like this will get fixed in https://github.com/neovim/neovim/pull/21474.

**Comment by akinsho** [comment] 2023-03-15 08:32
Think it's best to just wait for an upstream fix then since the alternative is a pretty extensive refactor to a soon to be deprecated function which is tech debt I'm not looking to take on.

**Comment by akinsho** [comment] 2023-04-03 08:01
Upstream PR is now merged https://github.com/neovim/neovim/pull/22867

**Closed by akinsho** 2023-04-03 08:01 UTC
Labels: bug, upstream
