### ISSUE TITLE
[Bug]: bad argument #1 to 'pairs' (table expected, got string)

### ISSUE THREAD

**Issue by fgheng** [akinsho/bufferline.nvim#436] opened 2022-06-01 15:27 UTC
### What happened?

1. Maximize terminals by click the 'Maximize' button 
![image](https://user-images.githubusercontent.com/50551377/171440680-3f385f1f-ec25-4abe-b0c8-6fddd8abbcdb.png)
2. Open any file in the nvim, open nvim-tree, open aerial
3. return the cursor to the file to be edited like as below
![image](https://user-images.githubusercontent.com/50551377/171440995-fe7af1ea-7c3d-4081-ba31-f8c16553522f.png)
5. shrink the terminal by click 'Maximize' button
6. the error appears
![image](https://user-images.githubusercontent.com/50551377/171441196-fe1acb59-8ec3-4ea1-bcb1-cf788c2ec667.png)

detail error:
```
E5108: Error executing lua ...te/pack/packer/opt/bufferline.nvim/lua/bufferline/ui.lua:560: bad argument #1 to 'pairs' (table expected, got string)                                                                                                                     
stack traceback:
        [C]: in function 'pairs'
        ...te/pack/packer/opt/bufferline.nvim/lua/bufferline/ui.lua:560: in function 'extend_highlight'
        ...te/pack/packer/opt/bufferline.nvim/lua/bufferline/ui.lua:589: in function 'to_tabline_str'
        ...te/pack/packer/opt/bufferline.nvim/lua/bufferline/ui.lua:669: in function 'join'
        ...te/pack/packer/opt/bufferline.nvim/lua/bufferline/ui.lua:716: in function 'tabline'
        .../site/pack/packer/opt/bufferline.nvim/lua/bufferline.lua:106: in function <.../site/pack/packer/opt/bufferline.nvim/lua/bufferline.lua:97>
```

![image](https://user-images.githubusercontent.com/50551377/171441332-3ac220af-53f3-496c-993d-6e41965d44c0.png)

### What did you expect to happen?

No mistakes

### Additional Information

Os: arch-linux
Desktop Environment: gnome 42.2
terminal: tilix, gnome terminal, wezterm
neovim version:
```
NVIM v0.8.0-dev+340-gb7d70de34
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az81-669

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

```

**Comment by akinsho** [comment] 2022-06-01 15:49
> No mistakes

I definitely don't promise this as a FOSS project, @fgheng can you explain what `maximise` does? I don't use Tilix, so I don't know what that button is doing?

Also, please note that when opening an issue here you should *always include your bufferline config* or at least the minimum to reproduce this isue 🙏🏿 without this there is little chance I can help.

**Comment by lorefnon** [comment] 2022-06-03 07:02
After updating to latest neovim I started to receive this error whenever I open nvim (in any terminal emulator - alacritty, tmux, gnome-terminal, guake)

My config: 

```
      options = {
        offsets = {
          { filetype = "NvimTree", text = "", padding = 1 },
          { filetype = "neo-tree", text = "", padding = 1 },
          { filetype = "Outline", text = "", padding = 1 },
        },
        buffer_close_icon = "",
        modified_icon = "",
        close_icon = "",
        max_name_length = 14,
        max_prefix_length = 13,
        tab_size = 20,
        separator_style = "thin",
      },

```

**Comment by akinsho** [comment] 2022-06-03 09:07
Can either of you provide me with a way to reproduce this that doesn't depend on an external plugin? I don't use `nvim-tree` and really would rather avoid having to avoid and set it up just reproduce this

**Comment by XXiaoA** [comment] 2022-06-04 02:59
I met the save bug.  
![IMG_20220604_104818](https://user-images.githubusercontent.com/62557596/171976074-35a327b6-0b80-4956-a46b-ee1531c09efb.jpg)

I ran `:NvimTreeToggle` after entering nvim and press `<CR>` to enter other files with nvim-tree. Then the bug was thrown. Weirdly, it doesn't throw the bug all the tim e, it seems to have a probability of happening, and a probability of not happening

 And the following is the most minimal configuration that I tested.  

```lua
local fn = vim.fn
local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
    fn.system({ "git", "clone", "--depth", "1", "https://hub.fastgit.xyz/wbthomason/packer.nvim.git", install_path })
    vim.cmd("packadd packer.nvim")
end

local all_plugins = {
    { "wbthomason/packer.nvim" },
    {
        "kyazdani42/nvim-tree.lua",
        requires = "kyazdani42/nvim-web-devicons",
    },
    { "akinsho/bufferline.nvim" },
}

require("packer").startup(function()
    for _, plugin in ipairs(all_plugins) do
        use(plugin)
    end
end)

vim.opt.termguicolors = true

local bufferline = require("bufferline")
bufferline.setup({
    options = {
        diagnostics = "nvim_lsp",
        offsets = {
            {
                filetype = "NvimTree",
                text = "File Explorer",
                highlight = "Directory",
                text_align = "left",
            },
        },
    },
})

local nvim_tree = require("nvim-tree")
nvim_tree.setup({
    respect_buf_cwd = true,
    update_cwd = true,
    update_focused_file = {
        enable = true,
        update_cwd = true,
    },
})
```

**Comment by akinsho** [comment] 2022-06-05 18:11
I've tried the above i.e. default config using nvim-tree, and I can't reproduce this issue I've also tried the setup in https://github.com/akinsho/bufferline.nvim/issues/436#issuecomment-1145653168, as mentioned when I try to open nvim tree on setup this doesn't work for me (it doesn't open automatically) 🤷🏿‍♂️ 

Will leave this as is till there is a consistent minimal mechanism to reproduce since atm I have no way of reproducing or debugging this

**Comment by reaz1995** [comment] 2022-06-07 09:49
the bug occur when buffer window is too small, to reproduce just resize terminal window, once buffer tabs from the left meet tab groups from the right it explode with pretty long red error.

**Comment by akinsho** [comment] 2022-06-07 10:10
@reaz1995 is this happening on the *latest* tag of this plugin i.e. `v2.2.1` as I just released a fix for a similar issue this weekend #443

**Comment by reaz1995** [comment] 2022-06-07 10:31
@akinsho  was tracking down the bug, it happen inside ui:
```
---@param list Segment[][]
local function join(list)
  local str = ""
  for _, item in pairs(list) do
    str = str .. to_tabline_str(item)
  end
  return str
end
```
the extracted item is a string instead of key value pair, but i may be wrong, never used lua before..

Updated plugin now
```
 ✓ Updated akinsho/bufferline.nvim: e2b1e99..c78b3ec
  URL: https://github.com/akinsho/bufferline.nvim
  Commits:
    c78b3ec version: 2.2.1 (2 days ago)
    60d8f4d fix(ui): return correct empty value from truncation (2 days ago)
    4b10426 fix(tabs): explicitly convert segments text attribute to string (#442) (3 days ago)
    ee7b723 fix(highlights): only set cterm values if not termguicolors (4 days ago)
    e9697f7 chore(github): add feature request template (6 days ago)
    e5a468b chore(github): add checkbox to ensure past issues checked (6 days ago)
    b08e789 chore(github): make config a required field for bug reports (6 days ago)
```

everything works correct now

**Comment by akinsho** [comment] 2022-06-07 10:54
Okay I'll close this out then, if anybody *on the latest tag* still has this issue comment back here and I'll re-open

**Closed by akinsho** 2022-06-07 10:54 UTC
Labels: bug, needs clarification
