### ISSUE TITLE
[Bug]: selected separator uses color for separator instead of separator_selected

### ISSUE THREAD

**Issue by Tyson453** [akinsho/bufferline.nvim#536] opened 2022-09-05 22:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The separator for the selected buffer is the color value for `highlight.separator` instead of `highlight.separator_selected`.

### What did you expect to happen?

I expect the separator for the selected buffer to be the color value associate with `highlight.separator_selected`.

### Config

local status, bufferline = pcall(require, "bufferline")
if not status then
    return 
end

bufferline.setup {
    options = {
        numbers = "none",
        close_command = "Bdelete! %d",
        right_mouse_command = "Bdelete! %d",
        left_mouse_command = "buffer %d",
        middle_mouse_command = nil,

        indicator = {
            icon = "▎",
            style = "icon",
        },
        buffer_close_icon = "",
        -- buffer_close_icon = '',
        modified_icon = "●",
        close_icon = "",
        -- close_icon = '',
        left_trunc_marker = "",
        right_trunc_marker = "",

        max_name_length = 30,
        max_prefix_length = 30,
        tab_size = 21,
        diagnostics = false,
        diagnostics_update_in_insert = false,

        offsets = { { filetype = "NvimTree", text = "", padding = 1 } },
        show_buffer_icons = true,
        show_buffer_close_icons = true,
        show_close_icon = true,
        show_tab_indicators = true,
        persist_buffer_sort = true,
        separator_style = "thin",
        enforce_regular_tabs = true,
        always_show_bufferline = true,

    },
    highlights = {
        fill = {
            fg = { attribute = "fg", highlight = "<#ff0000>" },
            bg = { attribute = "bg", highlight = "TabLine" },
        },
        background = {
            fg = { attribute = "fg", highlight = "TabLine" },
            bg = { attribute = "bg", highlight = "TabLine" },
        },

        buffer_selected = {
            fg = {attribute='fg',highlight='#ff0000'},
            bg = {attribute='bg',highlight='#0000ff'},
        },
        buffer_visible = {
            fg = { attribute = "fg", highlight = "TabLine" },
            bg = { attribute = "bg", highlight = "TabLine" },
        },

        close_button = {
            fg = { attribute = "fg", highlight = "TabLine" },
            bg = { attribute = "bg", highlight = "TabLine" },
        },
        close_button_visible = {
            fg = { attribute = "fg", highlight = "TabLine" },
            bg = { attribute = "bg", highlight = "TabLine" },
        },
        -- close_button_selected = {
        --   fg = {attribute='fg',highlight='TabLineSel'},
        --   bg ={attribute='bg',highlight='TabLineSel'}
        --   },

        tab_selected = {
            fg = { attribute = "fg", highlight = "Normal" },
            bg = { attribute = "bg", highlight = "Normal" },
        },
        tab = {
            fg = { attribute = "fg", highlight = "TabLine" },
            bg = { attribute = "bg", highlight = "TabLine" },
        },
        tab_close = {
            -- fg = {attribute='fg',highlight='LspDiagnosticsDefaultError'},
            fg = { attribute = "fg", highlight = "TabLineSel" },
            bg = { attribute = "bg", highlight = "Normal" },
        },

        duplicate_selected = {
            fg = { attribute = "fg", highlight = "TabLineSel" },
            bg = { attribute = "bg", highlight = "TabLineSel" },
            italic = true,
        },
        duplicate_visible = {
            fg = { attribute = "fg", highlight = "TabLine" },
            bg = { attribute = "bg", highlight = "TabLine" },
            italic = true,
        },
        duplicate = {
            fg = { attribute = "fg", highlight = "TabLine" },
            bg = { attribute = "bg", highlight = "TabLine" },
            italic = true,
        },

        modified = {
            fg = { attribute = "fg", highlight = "TabLine" },
            bg = { attribute = "bg", highlight = "TabLine" },
        },
        modified_selected = {
            fg = { attribute = "fg", highlight = "Normal" },
            bg = { attribute = "bg", highlight = "Normal" },
        },
        modified_visible = {
            fg = { attribute = "fg", highlight = "TabLine" },
            bg = { attribute = "bg", highlight = "TabLine" },
        },

        separator = {
            fg = { attribute = "fg", highlight = "TabLine" },
            bg = { attribute = "bg", highlight = "TabLine" },
        },
        separator_selected = {
            fg = { attribute = "fg", highlight = "DevIconC" },
            bg = { attribute = "bg", highlight = "DevIconC" },
        },
        separator_visible = {
            fg = {attribute='fg',highlight='DevIconC'},
            bg = {attribute='bg',highlight='DevIconC'}
        },
        indicator_selected = {
            fg = { attribute = "fg", highlight = "DevIconC" },
            bg = { attribute = "bg", highlight = "DevIconC" },
        },
   },
}

### Additional Information

...

**Comment by akinsho** [comment] 2022-09-08 14:25
@Tyson453 I've looked through the code and I don't see where there is any issue, I can also not tell from the above issue what exactly you are seeing that is incorrect. Based on the config above you have overriden the values of separator anyway so I wouldn't expect them to be anything other than what you set

**Comment by akinsho** [comment] 2022-09-19 11:00
Closing this out as there's been no further clarification and I can't reproduce this

**Closed by akinsho** 2022-09-19 11:00 UTC
Labels: bug
