### ISSUE TITLE
bufferline shows name of file which is closed

### ISSUE THREAD

**Issue by notwidow** [akinsho/bufferline.nvim#564] opened 2022-09-22 18:04 UTC
Hi, 
**ISSUE**
- I open file in neovim and it is one file so bufferline does not show up and then i open or split with another file and bufferline appears with 2 file names. 
- But when i close one file then bufferline still shows 2 file names and does not disappear ....
**STEPS TO REPRODUCE**
- set showtabline = 2 (just to show when there are more than one files open)
- open neovim with a file and then split or open another file within neovim.
- bufferline will show up with both file names 
- then close one file and bufferline will not disappear and will be still showing both file names.
**NOTE**
- I opened upto 5 files and closed all except one and you know it was still showing 5 file names and was not disappearing.
**INFO**
- NVIM v0.7.2
 Build type: Release
 LuaJIT 2.1.0-beta3
 Compiled by builduser
- OS: Arch Linux

**Comment by akinsho** [comment] 2022-09-22 18:26
@notwidow this is working as intended and I believe this issue is likely a misunderstanding of how neovim works. You should have a look at neovim's documentation about tabpages, windows and buffers for a better understanding.

When you open a file in neovim this is loaded into memory, you have the option of closing window it was loaded into or switching away from it. This *does not remove the file*, using `q` *does not remove the file*. The way to remove it is to use the `:bdelete` or `:bwipeout` command. When a file is truly closed i.e. removed from memory (more or less) it will be removed from bufferline.

**Closed by akinsho** 2022-09-22 18:26 UTC

**Comment by notwidow** [comment] 2022-09-22 18:39
> @notwidow this is working as intended and I believe this issue is likely a misunderstanding of how neovim works. You should have a look at neovim's documentation about tabpages, windows and buffers for a better understanding.
> 
> When you open a file in neovim this is loaded into memory, you have the option of closing window it was loaded into or switching away from it. This _does not remove the file_, using `q` _does not remove the file_. The way to remove it is to use the `:bdelete` or `:bwipeout` command. When a file is truly closed i.e. removed from memory (more or less) it will be removed from bufferline.

okay thank you, yes i misunderstood
