### ISSUE TITLE
separator goes white when opening nvimtree, telescope and split window 

### ISSUE THREAD

**Issue by razamd784** [akinsho/bufferline.nvim#807] opened 2023-09-01 21:29 UTC
[Screen Recording 2023-09-02 at 2.53.37 AM.zip](https://github.com/akinsho/bufferline.nvim/files/12501575/Screen.Recording.2023-09-02.at.2.53.37.

### here is my buffer line config

local status, bufferline = pcall(require, "bufferline")
if not status then
	return
end

bufferline.setup({
	options = {
		mode = "buffers",
		separator_style = "slant",
		-- separator_style = { "", "" },
		themable = true,
		always_show_bufferline = false,
		show_buffer_close_icons = false,
		-- show_buffer_icons = true,
		show_close_icon = false,
		color_icons = true,
		modified_icon = "●",
		close_command = "bdelete! %d",
		show_buffer_icons = true,
		-- get_element_icon = true,
		-- show_tab_indicators = true,
		-- show_duplicate_prefix = true,
		enforce_regular_tabs = false,
		persist_buffer_sort = true,
		offsets = {
			{
				filetype = "undotree",
				text = "Undotree",
				highlight = "PanelHeading",
				padding = 1,
			},
			{
				filetype = "NvimTree",
				text = "File Explorer",
				highlight = "PanelHeading",
				padding = 1,
			},
			{
				filetype = "DiffviewFiles",
				text = "Diff View",
				highlight = "PanelHeading",
				padding = 1,
			},
			{
				filetype = "flutterToolsOutline",
				text = "Flutter Outline",
				highlight = "PanelHeading",
			},
			{
				filetype = "lazy",
				text = "Lazy",
				highlight = "PanelHeading",
				padding = 1,
			},
		},
		hover = {
			enabled = false, -- requires nvim 0.8+
			delay = 200,
			reveal = { "close" },
		},
		sort_by = "id",
		diagnostics = "nvim_lsp",
		diagnostics_update_in_insert = false,
		-- diagnostics_indicator = function(count, level, diagnostics_dict, context)
		-- 	local icon = level:match("error") and " " or " "
		-- 	return " " .. icon .. count
		-- end,
	},
	highlights = {
		separator = {
			fg = "#073642",
			bg = "#002b36",
		},
		separator_selected = {
			fg = "#073642",
		},
		background = {
			fg = "#657b83",
			bg = "#002b36",
		},
		buffer_selected = {
			fg = "#fdf6e3",
			bold = true,
		},
		fill = {
			bg = "#073642",
		},
	},
})
I don't know if this is a problem or I don't know how to do that

**Comment by akinsho** [comment] 2023-09-03 07:21
@razamd784 as a general rule I do not debug individuals configs and issues with colours these issues are almost always due to configuration problems or colorscheme issues.

What you are describing sounds like a mixture of the above and your use of some other plugins. If you are able to narrow things down to a specific bug in this plugin (note the colours you get are a function of your config and not a bug) please post back otherwise I'm closing this issue

**Closed by akinsho** 2023-09-03 07:21 UTC
