### ISSUE TITLE
[Bug]: Buffer component changes size when entering buffer pick mode

### ISSUE THREAD

**Issue by HumblePresent** [akinsho/bufferline.nvim#217] opened 2021-09-09 03:41 UTC
### What happened?

When entering buffer pick mode components of a specific size change length. From what I can tell this only happens to components with a buffer name 9 characters long and a buffer icon that uses more than a single cell (I am using icons with 2 cells but 3 appears to produce the issue as well). It looks like an extra space of padding is added to the left of the icon and to the right of the buffer name upon entering buffer pick mode. I have included a video of what I am experiencing as well

https://user-images.githubusercontent.com/60856003/132617414-b50bfc8b-2f04-4a00-8cb2-ed8deb09c742.mp4

Based on my testing, this appears to be a regression from the refactor commit listed below .

### What did you expect to happen?

The component does not change length in buffer pick mode.

### Additional Information

...

### commit

0b1d0f034192f7d38567451fb7234f8ea3678d52

**Comment by akinsho** [comment] 2021-09-09 08:30
@HumblePresent I've pushed what I hope is a fix for this in the latest commit. Can you try it out and if it works, close out this issue 👍🏿

**Comment by HumblePresent** [comment] 2021-09-10 01:31
@akinsho I just tested the latest on master and it looks like my original issue is resolved but now certain components don't have any padding on either side as seen in the screenshot

![bufferline_217](https://user-images.githubusercontent.com/60856003/132784240-9bfe8810-2e95-4fd3-89a0-f9e19eea9a4d.png)

I'm not sure if that is intended or not but it seems like different behavior than I have seen before.

**Comment by akinsho** [comment] 2021-09-10 06:51
@HumblePresent I think if the main bug in this issue is resolved we should close it, regarding the other issue you are I cannot reproduce it, my buffers have padding. So I suggest we close this issue and if/when you figure out how to reproduce it, you open a new issue with some steps to reproduce, and I'll take a look.

**Comment by ram02z** [comment] 2021-09-10 10:35
@akinsho I think I am also experiencing a similar issue as @HumblePresent. My buffers seems to have different sizes, I have tried changing `enforce_regular_tabs` to true, but I don't think that's the problem because I had padding before without having to set it to true.


![image](https://user-images.githubusercontent.com/59267627/132840971-fcc738ce-e6ca-4d44-8de8-0f23b596f9d6.png)

**Comment by akinsho** [comment] 2021-09-10 11:09
@ram02z it's very possible that there's been a regression somewhere, yesterday's commits included the largest refactor I've done on this plugin since I first wrote it to accommodate some new features but I can't fix the issue without a clear way to reproduce it. Can either of you share your bufferline configs (just the setup bit) and a list of filenames that causes this issue. On my end I don't see the padding issue so it must be a configuration option I don't use causing the problem

**Comment by akinsho** [comment] 2021-09-10 11:18
Ah I found the issue, it relates to having the `show_buffer_close_icons` set to `false` if you enable them it works which is why I didn't see the issue.

**Comment by ram02z** [comment] 2021-09-10 11:27
> 
> 
> Ah I found the issue, it relates to having the `show_buffer_close_icons` set to `false` if you enable them it works which is why I didn't see the issue.

Yeah, I had `show_buffer_close_icons` set to `false`, setting it to `true` does resolve the issue.

**Comment by akinsho** [comment] 2021-09-10 11:41
I've just pushed a fix and optimistically closed the issue since I believe it should be resolved now. Let me know if I was too quick and it's still there 😅

**Closed** 2021-09-10 11:40 UTC
Labels: bug

**Comment by ram02z** [comment] 2021-09-10 11:47
@akinsho It works now, thanks for the quick fix!

**Comment by HumblePresent** [comment] 2021-09-11 03:30
Working for me as well. Thanks @akinsho!
