### ISSUE TITLE
[Bug]: Sidebar offset is not honored when closing a buffer

### ISSUE THREAD

**Issue by badloop** [akinsho/bufferline.nvim#638] opened 2022-12-21 19:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a sidebar is open (ex: nvim-tree, Neo-tree), and multiple buffers are open, closing one of the buffers will cause buffer line to use the full width of the window to display rather than continuing to honor the configured offset for the sidebar.

### What did you expect to happen?

Closing a buffer would keep the buffer line displayed with the configured offset if the sidebar is visible

### Config

```lua
require("bufferline").setup {
    options = {
        buffer_close_icon = '',
        mode = 'buffers',
        --        separator_style = 'slant',
        indicator = {
            style = 'underline',
        },
        offsets = {
            {
                filetype = "neo-tree",
                text = "File Explorer",
                separator = true,
                padding = 1
            }
        }
    },
}

```

**Comment by Congee** [comment] 2022-12-28 21:00
It may help to customize the closing behavior with bufdelete.nvim by checking vim.bo.filetype. Here's an example config
```lua
local sidebar = 'coc-explorer';
require('bufferline').setup {
    options = {
        offsets = {
            {
                filetype = sidebar,
                highlight = "Directory",
                text_align = "center"
            }
        },
        left_mouse_command = function(bufnr)
            if vim.bo.filetype ~= sidebar then
                vim.cmd("buffer " .. bufnr)
            end
        end,
        middle_mouse_command = function(bufnr)
            require('bufdelete').bufdelete(bufnr, true)
        end,
    },
}
local map = function(key, bufnr)
    local fn = function()
        if vim.bo.filetype ~= sidebar then
            require('bufferline').go_to_buffer(bufnr, true)
        end
    end

    vim.keymap.set('n', key, fn, { silent = true })
end
map("<M-1>", 1)
map("<M-2>", 2)
map("<M-3>", 3)
map("<M-4>", 4)
map("<M-5>", 5)
map("<M-6>", 6)
map("<M-7>", 7)
map("<M-8>", 8)
map("<M-9>", 9)
map("<M-0>", -1)
vim.cmd [[ nnoremap <silent> <leader>q :Bdelete<CR>]]
```

**Comment by akinsho** [comment] 2023-02-09 10:17
I'm unable to reproduce this, an important factor here will be how those buffers are actually getting closed. If you're still experiencing this please comment on here with a step by step set of instructions on how to reproduce this and I'll have a look when I can

**Closed by akinsho** 2023-02-09 10:17 UTC
Labels: bug
