### ISSUE TITLE
[Bug]: Current tab highlighting looks broken

### ISSUE THREAD

**Issue by Integralist** [akinsho/bufferline.nvim#486] opened 2022-07-26 16:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current tab highlighting looks broken...
<img width="530" alt="Screenshot 2022-07-26 at 17 25 44" src="https://user-images.githubusercontent.com/180050/181060407-9403add3-377d-44bb-b550-6d727aec78a1.png">

### What did you expect to happen?

I expected a nicer tab highlight, something more aligned to what is in the project README examples.

### Config

```lua
use { "akinsho/bufferline.nvim",
  tag = "v2.*",
  requires = "kyazdani42/nvim-web-devicons",
  config = function()
    require("bufferline").setup({
      options = {
        mode = "tabs"
      }
    })
  end
}
```

### Additional Information

I'm using the Alacritty terminal emulator and the latest NeoVim with the latest plugin version.

My config can be found here (in case it helps):
https://github.com/Integralist/dotfiles/tree/main/.config/nvim

**Comment by akinsho** [comment] 2022-07-27 06:59
@Integralist this issue doesn't really provide *any actionable information at all,* I can see that the highlighting looks different from what the default behaviour should be, but this is not the default behaviour of this plugin. In all likelihood you are using a theme and the colorscheme author has changed settings I often advise against changing for this exact reason, or you are not using termguicolors, or you are missing some basic highlight groups.

In any case, this is not actionable, and I'd rather not debug your config since I really don't have capacity to investigate individual user configs. I'd recommend trialling other themes to see if the behaviour changes

**Comment by Integralist** [comment] 2022-07-27 13:08
So I was seeing this with all the colourschemes I tried.

I then tried creating a reduced test case of my config (e.g. remove all config setup except for this plugin) but I was still seeing the issue. 

I then tried in the macOS terminal emulator and although the colour schemes are completely messed up in that terminal it looked like the weird highlight wasn't showing. Now that could be because the rest of the colourscheme was totally broken but it's more likely something to do with the Alacritty terminal.

**Comment by akinsho** [comment] 2022-07-27 15:02
@Integralist the macOS terminal doesn't support true colours I think, i.e. termguicolors won't work, so this plugins will also not work. You need to be using termguicolors otherwise you will have to set all the cterm colours yourself. Can you try another terminal emulator to narrow down the issue?

**Comment by Integralist** [comment] 2022-07-28 19:34
OK so everything works fine _except_ when run inside tmux. When running neovim in tmux, only then does the tab issue appear.

**Comment by akinsho** [comment] 2022-07-28 19:57
Ah... I don't use tmux any more, but have done historically, and I know you have to jump through some hoops to make sure colours work correctly with neovim. You can have a look at my tmux config in my dotfiles repo there might be something in there that would help but since this issue relates to an external tool I'll close this out, hopefully you can find a solution for this though and feel free to post it back here.

**Closed by akinsho** 2022-07-28 19:57 UTC
Labels: bug

**Comment by Integralist** [comment] 2022-07-28 20:37
Thanks I'll take a look but maybe this is the time for me to lean into the terminal support in neovim + your toggleterm plugin I've just discovered. 

I normally am working across multiple projects at the same time, which is why tmux is so useful to me.

I already am a heavy user of vim tabs and so to mimic tmux windows would mean only using tabs with `:lcd` (as alacrity doesn't support tabs).

**Comment by JamesTiberiusKirk** [comment] 2022-08-08 07:36
I have the same problem. Fine outside tmux and broken inside. However, whats more weird is that I use the same dot files across mac and linux (also use alacritty on both) and this probled only shows up on lunx.
@Integralist Did you ever manage to find the issue on your side?

**Comment by Integralist** [comment] 2022-08-08 07:39
Nope. Afraid not. After 10+ years of using tmux and occasionally having to fight annoying issues like this I decided to just bite the bullet and switch to https://zellij.dev/ where the colour issues disappeared.

**Comment by JamesTiberiusKirk** [comment] 2022-08-08 09:36
@Integralist ok, thanks for the shout. might give it a go myself at some point

**Comment by lnhrnndz** [comment] 2022-08-10 15:58
The issue is actually with using italics in tmux, not with the colors.

To fix it disable italics for `buffer_selected` in your bufferline config

``` lua
require("bufferline").setup({
  highlights = {
    buffer_selected = {
      gui = "bold"
    }
  }
})
```
