### ISSUE TITLE
[Feature Request]: Add buffername in new window when splitting it vertically.

### ISSUE THREAD

**Issue by nishu-murmu** [akinsho/bufferline.nvim#392] opened 2022-04-20 19:16 UTC
### What happened?

I saw while splitting the window vertically, the buffername is still inside the other window, IS there way to do that like in other editors
![bufferline](https://user-images.githubusercontent.com/71123337/164304594-4f33d6b6-3982-4396-a296-fc6ca9fb5690.png)

### What did you expect to happen?

Expected behaviour:
![subl](https://user-images.githubusercontent.com/71123337/164305267-db9df14a-f8ac-43b4-b437-e7f55ba232d5.png)

### Additional Information

...

**Comment by akinsho** [comment] 2022-04-20 22:06
@nishu-murmu this is actually a duplicate of #348 please have a read of that issue which explains most of my rationale for why this feature is not really very useful apart from as eye candy

**Comment by akinsho** [comment] 2022-04-20 22:07
Also I suggest you look into https://github.com/b0o/incline.nvim if this is about being able to recognise which window is which

**Comment by akinsho** [comment] 2022-04-21 07:10
Going to close this out as a duplicate of #348 hopefully you've read through that issue and understand why but feel free to ask questions on here or more importantly suggest solutions to the points I raised in that issue.

**Closed by akinsho** 2022-04-21 07:10 UTC
Labels: bug, duplicate
